# Site settings
title: El KuKu liest
email: elkuku.liest@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  El KuKu liest gern =;)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  elkukuliest

# Build settings
markdown: kramdown
